In [2]:
pip install quandl --no-warn-script-location

Note: you may need to restart the kernel to use updated packages.


In [3]:
import quandl

In [4]:
quandl.ApiConfig.api_key = "iTpxtDeRE8aWAzzsm-PV"

In [5]:
df = quandl.get("EOD/AAPL", authtoken="iTpxtDeRE8aWAzzsm-PV")
df

Open     High      Low    Close      Volume  Dividend  Split  \
Date                                                                         
2013-09-03  493.10  500.600  487.350  488.580  11854600.0       0.0    1.0   
2013-09-04  499.56  502.240  496.280  498.691  12322600.0       0.0    1.0   
2013-09-05  500.25  500.680  493.640  495.270   8441700.0       0.0    1.0   
2013-09-06  498.44  499.380  489.950  498.220  12840200.0       0.0    1.0   
2013-09-09  505.00  507.920  503.480  506.170  12167400.0       0.0    1.0   
...            ...      ...      ...      ...         ...       ...    ...   
2017-12-21  174.17  176.020  174.100  175.010  20949896.0       0.0    1.0   
2017-12-22  174.68  175.424  174.500  175.010  16349444.0       0.0    1.0   
2017-12-26  170.80  171.470  169.679  170.570  33185536.0       0.0    1.0   
2017-12-27  170.10  170.780  169.710  170.600  21498213.0       0.0    1.0   
2017-12-28  171.00  171.850  170.480  171.080  16480187.0       0.0    1.0   

             Adj_Open   Adj_High    Adj_Low  Adj_Close   Adj_Volume  
Date                                                                 
2013-09-03  15.596272  15.833489  15.414405  15.453308  331928800.0  
2013-09-04  15.800595  15.885361  15.696852  15.773109  345032800.0  
2013-09-05  15.822419  15.836020  15.613351  15.664906  236367600.0  
2013-09-06  15.765170  15.794902  15.496640  15.758212  359525600.0  
2013-09-09  15.972657  16.065014  15.924581  16.009663  340687200.0  
...               ...        ...        ...        ...          ...  
2017-12-21  41.836857  42.281240  41.820043  42.038631   83799584.0  
2017-12-22  41.959363  42.138077  41.916125  42.038631   65397776.0  
2017-12-26  41.027359  41.188298  40.758087  40.972112  132742144.0  
2017-12-27  40.859214  41.022555  40.765534  40.979318   85992852.0  
2017-12-28  41.075401  41.279577  40.950493  41.094617   65920748.0  

[1090 rows x 12 columns]

In [6]:
df.isna().sum()

Open          0
High          0
Low           0
Close         0
Volume        0
Dividend      0
Split         0
Adj_Open      0
Adj_High      0
Adj_Low       0
Adj_Close     0
Adj_Volume    0
dtype: int64

In [7]:
df['Split'].value_counts()

1.0    1089
7.0       1
Name: Split, dtype: int64

In [8]:
#High low percentage column
df['HL_PCT']=(df['Adj_High']-df['Adj_Low'])/df['Adj_Close']*100.0

In [9]:
df

Open     High      Low    Close      Volume  Dividend  Split  \
Date                                                                         
2013-09-03  493.10  500.600  487.350  488.580  11854600.0       0.0    1.0   
2013-09-04  499.56  502.240  496.280  498.691  12322600.0       0.0    1.0   
2013-09-05  500.25  500.680  493.640  495.270   8441700.0       0.0    1.0   
2013-09-06  498.44  499.380  489.950  498.220  12840200.0       0.0    1.0   
2013-09-09  505.00  507.920  503.480  506.170  12167400.0       0.0    1.0   
...            ...      ...      ...      ...         ...       ...    ...   
2017-12-21  174.17  176.020  174.100  175.010  20949896.0       0.0    1.0   
2017-12-22  174.68  175.424  174.500  175.010  16349444.0       0.0    1.0   
2017-12-26  170.80  171.470  169.679  170.570  33185536.0       0.0    1.0   
2017-12-27  170.10  170.780  169.710  170.600  21498213.0       0.0    1.0   
2017-12-28  171.00  171.850  170.480  171.080  16480187.0       0.0    1.0   

             Adj_Open   Adj_High    Adj_Low  Adj_Close   Adj_Volume    HL_PCT  
Date                                                                           
2013-09-03  15.596272  15.833489  15.414405  15.453308  331928800.0  2.711941  
2013-09-04  15.800595  15.885361  15.696852  15.773109  345032800.0  1.195129  
2013-09-05  15.822419  15.836020  15.613351  15.664906  236367600.0  1.421447  
2013-09-06  15.765170  15.794902  15.496640  15.758212  359525600.0  1.892738  
2013-09-09  15.972657  16.065014  15.924581  16.009663  340687200.0  0.877176  
...               ...        ...        ...        ...          ...       ...  
2017-12-21  41.836857  42.281240  41.820043  42.038631   83799584.0  1.097080  
2017-12-22  41.959363  42.138077  41.916125  42.038631   65397776.0  0.527970  
2017-12-26  41.027359  41.188298  40.758087  40.972112  132742144.0  1.050009  
2017-12-27  40.859214  41.022555  40.765534  40.979318   85992852.0  0.627198  
2017-12-28  41.075401  41.279577  40.950493  41.094617   65920748.0  0.800795  

[1090 rows x 13 columns]

In [10]:
#percentage Change Column
df['PCT_change']=(df['Adj_Close']-df['Adj_Open'])/df['Adj_Open']*100.0
df

Open     High      Low    Close      Volume  Dividend  Split  \
Date                                                                         
2013-09-03  493.10  500.600  487.350  488.580  11854600.0       0.0    1.0   
2013-09-04  499.56  502.240  496.280  498.691  12322600.0       0.0    1.0   
2013-09-05  500.25  500.680  493.640  495.270   8441700.0       0.0    1.0   
2013-09-06  498.44  499.380  489.950  498.220  12840200.0       0.0    1.0   
2013-09-09  505.00  507.920  503.480  506.170  12167400.0       0.0    1.0   
...            ...      ...      ...      ...         ...       ...    ...   
2017-12-21  174.17  176.020  174.100  175.010  20949896.0       0.0    1.0   
2017-12-22  174.68  175.424  174.500  175.010  16349444.0       0.0    1.0   
2017-12-26  170.80  171.470  169.679  170.570  33185536.0       0.0    1.0   
2017-12-27  170.10  170.780  169.710  170.600  21498213.0       0.0    1.0   
2017-12-28  171.00  171.850  170.480  171.080  16480187.0       0.0    1.0   

             Adj_Open   Adj_High    Adj_Low  Adj_Close   Adj_Volume    HL_PCT  \
Date                                                                            
2013-09-03  15.596272  15.833489  15.414405  15.453308  331928800.0  2.711941   
2013-09-04  15.800595  15.885361  15.696852  15.773109  345032800.0  1.195129   
2013-09-05  15.822419  15.836020  15.613351  15.664906  236367600.0  1.421447   
2013-09-06  15.765170  15.794902  15.496640  15.758212  359525600.0  1.892738   
2013-09-09  15.972657  16.065014  15.924581  16.009663  340687200.0  0.877176   
...               ...        ...        ...        ...          ...       ...   
2017-12-21  41.836857  42.281240  41.820043  42.038631   83799584.0  1.097080   
2017-12-22  41.959363  42.138077  41.916125  42.038631   65397776.0  0.527970   
2017-12-26  41.027359  41.188298  40.758087  40.972112  132742144.0  1.050009   
2017-12-27  40.859214  41.022555  40.765534  40.979318   85992852.0  0.627198   
2017-12-28  41.075401  41.279577  40.950493  41.094617   65920748.0  0.800795   

            PCT_change  
Date                    
2013-09-03   -0.916650  
2013-09-04   -0.173953  
2013-09-05   -0.995502  
2013-09-06   -0.044138  
2013-09-09    0.231683  
...                ...  
2017-12-21    0.482287  
2017-12-22    0.188917  
2017-12-26   -0.134660  
2017-12-27    0.293945  
2017-12-28    0.046784  

[1090 rows x 14 columns]

In [11]:
df.drop(['Open','High','Low','Close','Volume','Dividend','Split','Adj_Open','Adj_High','Adj_Low'],axis=1,inplace=True)

In [12]:
df

Adj_Close   Adj_Volume    HL_PCT  PCT_change
Date                                                    
2013-09-03  15.453308  331928800.0  2.711941   -0.916650
2013-09-04  15.773109  345032800.0  1.195129   -0.173953
2013-09-05  15.664906  236367600.0  1.421447   -0.995502
2013-09-06  15.758212  359525600.0  1.892738   -0.044138
2013-09-09  16.009663  340687200.0  0.877176    0.231683
...               ...          ...       ...         ...
2017-12-21  42.038631   83799584.0  1.097080    0.482287
2017-12-22  42.038631   65397776.0  0.527970    0.188917
2017-12-26  40.972112  132742144.0  1.050009   -0.134660
2017-12-27  40.979318   85992852.0  0.627198    0.293945
2017-12-28  41.094617   65920748.0  0.800795    0.046784

[1090 rows x 4 columns]

In [13]:
df.isna().sum()

Adj_Close     0
Adj_Volume    0
HL_PCT        0
PCT_change    0
dtype: int64

In [14]:
import math

In [15]:
col = 'Adj_Close'
out = math.ceil(0.01* len(df)) #taking 1 day out
out

11

In [16]:
df.fillna(-99999, inplace = True)
df['label']= df[col].shift(-out)

In [17]:
df

Adj_Close   Adj_Volume    HL_PCT  PCT_change      label
Date                                                               
2013-09-03  15.453308  331928800.0  2.711941   -0.916650  14.697375
2013-09-04  15.773109  345032800.0  1.195129   -0.173953  14.938388
2013-09-05  15.664906  236367600.0  1.421447   -0.995502  14.783722
2013-09-06  15.758212  359525600.0  1.892738   -0.044138  15.518464
2013-09-09  16.009663  340687200.0  0.877176    0.231683  15.469755
...               ...          ...       ...         ...        ...
2017-12-21  42.038631   83799584.0  1.097080    0.482287        NaN
2017-12-22  42.038631   65397776.0  0.527970    0.188917        NaN
2017-12-26  40.972112  132742144.0  1.050009   -0.134660        NaN
2017-12-27  40.979318   85992852.0  0.627198    0.293945        NaN
2017-12-28  41.094617   65920748.0  0.800795    0.046784        NaN

[1090 rows x 5 columns]

In [18]:
df['label'].isna().sum()

11

In [19]:
df=df.dropna()

In [20]:
df

Adj_Close   Adj_Volume    HL_PCT  PCT_change      label
Date                                                               
2013-09-03  15.453308  331928800.0  2.711941   -0.916650  14.697375
2013-09-04  15.773109  345032800.0  1.195129   -0.173953  14.938388
2013-09-05  15.664906  236367600.0  1.421447   -0.995502  14.783722
2013-09-06  15.758212  359525600.0  1.892738   -0.044138  15.518464
2013-09-09  16.009663  340687200.0  0.877176    0.231683  15.469755
...               ...          ...       ...         ...        ...
2017-12-06  40.597389  114240000.0  2.215668    0.901493  42.038631
2017-12-07  40.671853  102693232.0  0.903614    0.171567  42.038631
2017-12-08  40.683863   93420924.0  1.287123   -0.656930  40.972112
2017-12-11  41.476547  141095036.0  2.374472    2.050827  40.979318
2017-12-12  41.243546   77636920.0  0.541060   -0.261400  41.094617

[1079 rows x 5 columns]

In [21]:
import numpy as np
from sklearn.model_selection import train_test_split

In [22]:
x=np.array(df.drop(['label'],1))

In [23]:
x

array([[ 1.54533083e+01,  3.31928800e+08,  2.71194073e+00,
        -9.16649767e-01],
       [ 1.57731094e+01,  3.45032800e+08,  1.19512885e+00,
        -1.73953079e-01],
       [ 1.56649065e+01,  2.36367600e+08,  1.42144689e+00,
        -9.95502249e-01],
       ...,
       [ 4.06838634e+01,  9.34209240e+07,  1.28712287e+00,
        -6.56930025e-01],
       [ 4.14765465e+01,  1.41095036e+08,  2.37447154e+00,
         2.05082742e+00],
       [ 4.12435457e+01,  7.76369200e+07,  5.41059988e-01,
        -2.61399942e-01]])

In [24]:
y=np.array(df['label'])
y

array([14.69737466, 14.93838782, 14.78372189, ..., 40.97211179,
       40.979318  , 41.09461737])

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [46]:
#from sklearn.preprocessing import MinMaxScaler

In [47]:
#feature_scale= MinMaxScaler().fit(x_train)

In [48]:
#x_train_scaled= feature_scale.transform(x_train)

In [49]:
#x_test_scaled= feature_scale.transform(x_test)

In [50]:
print("shape of original dataset :", df.shape)
print("shape of input - training set", x_train.shape)
print("shape of output - training set", y_train.shape)
print("shape of input - testing set", x_test.shape)
print("shape of output - testing set", y_test.shape)

shape of original dataset : (1079, 5)
shape of input - training set (863, 4)
shape of output - training set (863,)
shape of input - testing set (216, 4)
shape of output - testing set (216,)


In [51]:
from sklearn.linear_model import LinearRegression

In [52]:
predictor = LinearRegression(n_jobs=-1) 
predictor.fit(x_train, y_train) 

LinearRegression(n_jobs=-1)

In [145]:
predictor.predict(x_test[:5]) 

array([27.16860509, 25.8709867 , 23.20169429, 25.89496068, 21.48383819])

In [146]:
np.array(y_test[:5])

array([27.6674374 , 26.373789  , 22.29844841, 27.90191179, 23.47266651])

In [59]:
predictor.score(x_train,y_train)

0.9663852458645319

In [60]:
predictor.score(x_test,y_test)

0.9640293227357328

In [61]:
from sklearn.model_selection import cross_val_score

In [62]:
cross_val_score(predictor,x,y,cv=5)

array([0.80713816, 0.83709046, 0.58619639, 0.73011498, 0.67250501])

In [167]:
predictor.score(x_test,y_test) , np.mean(cross_val_score(predictor,x,y,cv=5))

(0.9640293227357328, 0.7266089983350749)

In [56]:
from sklearn.metrics import mean_squared_error

In [147]:
y_pred=predictor.predict(x_test) 
tt=mean_squared_error(y_test,y_pred) 

In [168]:
tt

1.5627893654551486